name: Build Android AAB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - uses: android-actions/setup-android@v3
    - name: Build
      run: |
        cd mobile-app
        npm install --legacy-peer-deps
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/manoprotect-2025.keystore
        cd android
        echo "MYAPP_UPLOAD_STORE_FILE=manoprotect-2025.keystore" >> gradle.properties
        echo "MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> gradle.properties
        echo "MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> gradle.properties
        echo "MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> gradle.properties
        chmod +x gradlew
        ./gradlew bundleRelease --no-daemon
    - uses: actions/upload-artifact@v4
      with:
        name: ManoProtect-AAB
        path: mobile-app/android/app/build/outputs/bundle/release/*.aab
